account-id: bpyPt7Qr2Qbui3MJMgyzZ3WaQkyj6OkU
name: weather
summary: OpenWeather data published to MQTT, configured via confdb.
# The revision for this confdb-schema
# revision: 1
views:
  admin:
    summary: Read-write control view used by the custodian snap.
    rules:
    - request: weather
      storage: v1.weather
      access: read-write
  state:
    summary: Read-only view for observer snaps.
    rules:
    - request: weather
      storage: v1.weather
      access: read

body: |-
  {
    "storage": {
      "schema": {
        "v1": {
          "type": "map",
          "schema": {
            "weather": {
              "type": "map",
              "schema": {
                "api-key": {
                  "type": "string",
                  "visibility": "secret"
                },
                "location": {
                  "type": "map",
                  "schema": {
                    "lat": {
                      "type": "number",
                      "min": -90,
                      "max": 90
                    },
                    "lon": {
                      "type": "number",
                      "min": -180,
                      "max": 180
                    }
                  }
                },
                "poll-interval": {
                  "type": "int",
                  "min": 60
                },
                "mqtt": {
                  "type": "map",
                  "schema": {
                    "server": {
                      "type": "string"
                    },
                    "port": {
                      "type": "int",
                      "min": 1,
                      "max": 65535
                    },
                    "topic": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
