#!/bin/sh -e

logger -t "weatherstation.observe-view" "confdb weather view changed; restarting daemon"

if snapctl services weatherstation.weatherstationd | grep -q active; then
    snapctl restart weatherstation.weatherstationd || true
fi

exit 0
